languages = {
    'langEN': {
         '_versionNum': 'v1.3.0',
         '_versionFullName': 'RL-GARAGE PRE-BOT v1.3.0',
         '_confVersion': '0.0.2',
         '_newVerAlert': '\n\tNew Version is Available -->',
         '_menuMain': ["\t[ 1 ] START THE BOT", "\t[ 2 ] ITEM ALERTS", "\t[ 3 ] AUTO BUMPER", "\t[ 4 ] AUTO REPLY", "\t[ 5 ] SETTINGS", "\t[ 6 ] ABOUT"],
         '_menuItemAlerts': ["\t\t- [1] Add an Alert", "\t\t- [2] Edit Your Alert List", "\t\t- [3] Desktop Notifications ON/OFF","\t\t- [4] {} Item Alerts", "\t\t- [0] Exit"],
         '_menuAutoBumper': ["\t\t- [1] View Your Account", "\t\t- [2] Delete Your Account", "\t\t- [3] {} Auto Bumper", "\t\t- [4] FAST MODE - {}", "\t\t- [0] Exit"],
         '_menuAutoReply': ["\t\t- [1] View Your Account", "\t\t- [2] Delete Your Account", "\t\t- [3] {} Auto Reply", "\t\t- [4] Edit Your Reply", "\t\t- [5] Telegram Notifications ON/OFF", "\t\t- [0] Exit"],
         '_WYW': '\n\tWhat do you want to do? : ',
         '_input_Yes'   : 'y',
         '_input_No'    : 'n',
         '_input_Mail': '\t- Enter your RL-Garage e-mail?: ',
         '_input_Password': '\t- Enter your RL-Garage password?: ',
         '_warn_YesOrNO' : '\t>> Type Y(Yes) or N(No)',
         '_warn_MenuChild': "\n\t>> Choose from the menu!",
         '_warn_Menu': '\n\t>> Choose from the menu! [1][2][3][4][5][6]',
         '_warn_Mail': '\n\t>> Invalid E-Mail!',
         '_warn_Pw': '\n\t>> Your password must contain more than 5 and less than 129 characters!',
         '_warn_LoginInfo': '\t>> If your login information is wrong, the bot will not run..!!\n',
         '_warnLoginRetry': "\t>> Login failed! Retrying..",
         '_warn_hiUser': '\t>> Hi, {}! You have no active trades. Check your RL-Garage profile!',
         '_warn_InvInfo': '\n\t>> Rocket-League.com --> Your mail/password is incorrect or you have a connection problem !! :(\n',
         '_warn_BrowserErr': '\n\tCONNECTING ERROR: Google Chrome browser is not available on your system or you need to update it!\n',
         '_warn_BrowsersClose': "\n\t-- All Google Chrome windows will be closed! Do you want to continue? (Y / N): ",
         '_warn_RequestLimit': "\n\t>> Sorry, you have exceeded the request limits. Please try again later.",
         '_botRunning': '\n\t>> The Bot is running now..',
         '_downNewVer': '\n\tWould you like to download now? (Y / N): ',
         '_AB_on': '\n\t>> Auto bumper activated..',
         '_AB_off': '\n\t>> Auto bumper turned off..',
         '_AR_off': '\n\t>> Auto reply turned off..',
         '_AR_on': '\n\t>> Auto reply activated..',
         '_start_AB_Disabled': '\tAUTO BUMPER --> DISABLED - You need to activate!',
         '_start_AB_Enabled': "\tAUTO BUMPER --> ENABLED" +  "  " + "- Logging in Rocket-League.com!",
         '_start_AR_Disabled': "\tAUTO REPLY" + " " + " --> DISABLED - You need to activate!\n",
         '_start_AR_Enabled': "\tAUTO REPLY" + " " + " --> ENABLED " + " " + "- Logging in Rocket-League.com!\n",
         '_AB_working_slow': '\n\t>> [Auto Bumper] --> Currently Working! Your trade offers will be updated automatically. (NORMAL MODE)',
         '_AB_working_fast': '\n\t>> [Auto Bumper] --> Currently Working! Your trade offers will be updated automatically. (FAST MODE)',
         '_AR_working': "\n\t>> [Auto Reply] --> Currently Working! Your users will receive an auto-reply!",
         '_botStopped': "\n\t>> The bot has stopped working! :(",
         '_checkingBrowser': "\t>> Checking Google Chrome browser..",
         '_about': '\n\t>> You can contact me for bugs and requests.\n\t\tDiscord: Emrah#9685\n\t\tThank you for using the PRE-BOT\n\t\tCheck new version > github.com/mrhgvn/RL-GARAGE-PRE-BOT',
         '_pleaseWait': '\t>> Please wait..',
         '_infoTitle': '\n\t>> Your Account Informations',
         '_del_RLG': '\n\t>> Deleted your account..',
         '_rlg_LoginTitle': '\n\t>> Rocket-League.com login',
         '_startBot': '\t>> You can start the bot!',
         '_rlgInfoSaved': '\n\t>> Your account information has been saved!',
         '_choice': "\n\t[{}]: Make Your Choice: ",
         '_hiUser': '\t>> Hi, {}! You have {} active trades.',
         '_replyTextOpened': "\n\t>> Message text opened! Please edit, save and close..",
         '_replySent': " - Auto Reply Sent: "
 }
}

